### ISSUE TITLE
Update all fails

### ISSUE THREAD

**Issue by jaywehner** [th33xitus/kiauh#206] opened 2022-06-03 18:35 UTC
### Linux Distribution

MainsailOS pi 4's (two of them)

### What happened

Selecting A to update all doesn't work it says:

#=======================================================#
 Everything is already up-to-date! 
#=======================================================#

But it is not:
/=======================================================\
|     ~~~~~~~~~~~~~~ [ Update Menu ] ~~~~~~~~~~~~~~     |
|-------------------------------------------------------|
| a) [Update all]        |               |              |
|                        | Installed:    | Latest:      |
| Klipper & API:         |---------------|--------------|
  1) [Klipper]          | v0.10.0-419   | v0.10.0-440  |
  2) [Moonraker]        | v0.7.1-572    | v0.7.1-573   |
|                        |               |              |
| Klipper Webinterface:  |---------------|--------------|
  3) [Mainsail]         | v2.2.0-beta3  | v2.1.2       |
|  4) [Fluidd]           | v1.18.1       | v1.18.1      |
|                        |               |              |
| Touchscreen GUI:       |---------------|--------------|
|  5) [KlipperScreen]    |               |              |
|                        |               |              |
| Other:                 |---------------|--------------|
|  6) [PrettyGCode]      | v0.12.0-1     | v0.12.0-1    |
  7) [Telegram Bot]     | v1.4.3        | v1.4.3-2     |
|                        |------------------------------|
|  8) [System]           |  System up to date!          |
|-------------------------------------------------------|
|                       B) « Back                       |
\=======================================================/

### What did you expect to happen

the software to update

### How to reproduce

tested on two installs. Manual update each works as a work around

**Comment by th33xitus** [comment] 2022-06-03 18:38
duplicate of: https://github.com/th33xitus/kiauh/issues/204

**Closed by th33xitus** 2022-06-03 18:38 UTC
Labels: bug, duplicate
