### ISSUE TITLE
unable to install mjpg-streamer

### ISSUE THREAD

**Issue by dodolcool** [th33xitus/kiauh#284] opened 2023-01-08 09:34 UTC
### Linux Distribution

debian bullseye

### What happened

im unable to install mjpg-streamer (option number 10 i belive) it always say service not available.

### What did you expect to happen

it will be great if this feature work

### How to reproduce

run kiauh run option number 10

**Comment by th33xitus** [comment] 2023-01-08 09:45
Duplicate of #279 and #280.

**Closed by th33xitus** 2023-01-08 09:45 UTC
Labels: duplicate
