### ISSUE TITLE
Raspberry Pi no connection after attempting system updates with Kiauh.

### ISSUE THREAD

**Issue by domocorn** [th33xitus/kiauh#319] opened 2023-03-20 21:22 UTC
### Linux Distribution

Installed on a Raspberry Pi Zero W. PiOS Lite 32bit flashed using the official installer from Raspberry Pi and used a Ubuntu Linux virtual machine.

### What happened

Attempted to run the System Update option within Kiauh and the Pi gets part way through the installation, suddenly disconnects, and does not respond to pings. After waiting a while with no signs of life other than the solid green light on the board I power it down and when powering back on I get 7 flashes indicating an issue with the OS image. 

Instead of trying to repair the OS image I pull my config off and reflash the SD card. I then reinstall Kiauh and reinstall all the needed software to get back up and running. Installed everything again with no issue and then went back into the update section and tried to update Klipper and Moonraker as they were out of date already. I have now run into the same issue with no pings however this time the OS did not corrupt.

### What did you expect to happen

What should happen is the device should not disconnect or if the update is something that will cause a disconnect there should be a warning or something.

### How to reproduce

Run Kiauh and navigate to the Update section. If there is a system update try to simply update by selecting the option and running it. This has happened multiple times with the System Update option.

**Comment by th33xitus** [comment] 2023-03-20 21:33
This is likely no issue with KIAUH. You can see which commands get executed when running a system update from within KIAUH here: <https://github.com/th33xitus/kiauh/blob/master/scripts/utilities.sh#L376>
It's nothing more than the usual `sudo apt-get update --allow-releaseinfo-change && sudo apt-get upgrade -y`, nothing special is done.

Hence im closing this issue, as the reason for the update to not complete must be caused by something else.

**Closed by th33xitus** 2023-03-20 21:33 UTC
Labels: bug
